#!/bin/bash

## add new files to this list in
## lexigraphical order
declare -a dotfiles=(".bash_aliases"
                     ".gitconfig"
                     ".gitignore"
                     ".rtorrent.rc"
                     ".tmux.conf"
                     ".spacemacs"
                     ".vimrc")

## create sybolic links to the files if
## they do not already exist
for i in "${dotfiles[@]}"
do
    if [ -e $HOME/$i ];
    then
        echo "File $i already exists!"
    else
        ln -s $HOME/.dotfiles/$i $HOME/
    fi
done
