#!/bin/bash

## add new files to this list in
## lexigraphical order
declare -a dotfiles=(".bash_aliases"
                     ".curlrc"
                     ".gdbinit"
                     ".gitconfig"
                     ".gitignore"
                     ".rtorrent.rc"
                     ".tmux.conf"
                     ".spacemacs"
                     ".vimrc")

## create sybolic links to the files if
## they do not already exist
for i in "${dotfiles[@]}"
do
  ln -s $HOME/.dotfiles/$i $HOME/
done

## handle non-standard configurations and
## directories here

## .vim directory
if [ ! -d $HOME/.vim ];
then
  mkdir $HOME/.vim
fi

ln -s $HOME/.dotfiles/.vim/colors $HOME/.vim/

## .emacs.d directory
ln -s $HOME/.dotfiles/.emacs.d/private $HOME/.emacs.d/
